# Default shell
SHELL := /bin/bash

# Including makefiles
-include Makefile.vars
-include Makefile.api
-include Makefile.docs

# commands
MKDIR := mkdir -p
MOVE := mv -f
REMOVE := rm -rf
COPY := cp -R
GO_BUILD := CGO_ENABLED=0 go build -o

# vars
shared_docs := .shared/.docs

# generates the documentation site with the autogenerated api
docs: docs-site docs-api docs-serve

## cleans the build directories
clean-build:
	$(REMOVE) bin $(SHARED_PATH)

## compiles the config parser
build: build-self build-config-parser build-errors

# copies itself to the shared dir
build-self:
	$(REMOVE) $(shared_docs)
	$(MKDIR) $(shared_docs)
	$(COPY) ./* $(shared_docs) || true
	$(REMOVE) $(shared_docs)/.shared

# compiles the config parser
build-config-parser:
	@$(MKDIR) bin;
	$(GO_BUILD) bin/config src/*.go

# generates the errors page
build-errors:
	$(MAKE) -s docs DESTINATION_PATH=$(ERRORS_PATH)
